### ISSUE TITLE
Minor: White hover button state

### ISSUE THREAD

**Issue by itsgg** [mthadley/outlander-ui#4]
Please check the screenshot. Thanks for an awesome theme. 

![screen shot 2016-07-16 at 11 14 08 pm](https://cloud.githubusercontent.com/assets/1752073/16896233/246926ae-4bab-11e6-986c-3ed3b57fb796.png)

**Comment by itsgg** [comment]
.settings-view .config-menu .button-area {
  .btn:focus {
    color: #eee;
    background-color: #232323;
  }
}

This style has to be overridden

**Comment by mthadley** [comment]
Thanks for reporting this! I'll try and take a look soon.
