### ISSUE TITLE
Splitting editor leaves ui blurred in Atom 14.x

### ISSUE THREAD

**Issue by dbstraffin** [mthadley/outlander-ui#6]
If you split up/down/left/right, the ui blurs and then fails to de-blur.  It started with Atom 14.0 and is still happening with 14.1.  The built in themes don't appear to have this issue which is why I'm reporting it here.  I'm running Ununbu 16.04 (i3wm).

![2017-02-10-115055_1078x917_scrot](https://cloud.githubusercontent.com/assets/15882893/22835900/58af9b06-ef88-11e6-996f-7e9b97fb6170.png)
![2017-02-10-115853_745x185_scrot](https://cloud.githubusercontent.com/assets/15882893/22835901/58b43e18-ef88-11e6-93b0-c77ecf9f8e22.png)

**Comment by mthadley** [comment]
Thanks for reporting this!

I see the same issue. It should only blur for things like modals or pop-ups (like `Ctrl-P`, etc.), however the logic was somewhat hacky as I was not able to a perfect API to detect when these are opened. I'll take a look.

I think I might also add a configuration option to disable the blur, and possibly even have it disabled by default in the future.

**Comment by dbstraffin** [comment]
A config option for the blur would be cool.  Thanks for the quick response and providing a great theme!
